### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by maikeldotuk** [mopidy/mopidy-youtube#100]
Title says it all

**Comment by gilgongo** [comment]
It depends. I think some would say so, but see https://github.com/mopidy/mopidy-youtube/issues/87#issuecomment-414153256

**Comment by kingosticks** [comment]
In terms of development the readme states:

> Mopidy-YouTube is currently kept on life support by the Mopidy core developers. It is in need of a more dedicated maintainer.

**Comment by maikeldotuk** [comment]
Thanks God for that, I forgot how to read. On 25 Feb 2019 10:11, Nick Steel <notifications@github.com> wrote:In terms of development the readme states:

Mopidy-YouTube is currently kept on life support by the Mopidy core developers. It is in need of a more dedicated maintainer.

**Comment by kingosticks** [comment]
And on that note I think we are done here. If you have a specific bug report or feature request then open another issue.
