### ISSUE TITLE
`None` may be returned from YoutubeLibraryProvider::lookup

### ISSUE THREAD

**Issue by MrPepperoni** [mopidy/mopidy-youtube#28]
As described [here] (https://github.com/mopidy/mopidy/issues/1188), resolve_url might fail for certain youtube search results. For me, searching for "Dangervisit" returns mainly unavailable videos, however that might be dependant on my geographical location.
If that happens, the lookup returns [ None ] instead of [], in turn causing an exception in MpdSession.

Probably it'd be better to check the results in YoutubeLibraryProvider::search, however it seemed to seriously slow the search down, oftentimes resulting in client disconnection.

**Comment by jodal** [comment]
Fixed by #35.
