### ISSUE TITLE
Specifying preferred audio codec

### ISSUE THREAD

**Issue by kgudka** [mopidy/mopidy-youtube#36]
Thanks for writing this great extension.

I'm running OS X and am having some gstreamer issues whereby for some videos that have their best audio source as ogg files, gstreamer cannot decode them for some reason even though I have the various gstreamer ogg decoder plugins installed. 

I have managed to get around this by modifying the call to getbestaudio in backend.py so that it takes the argument as follows getbestaudio(preftype="m4a").

Could configuration options be added to specify preferred audio/video codecs? 

My actual problem looks like a gstreamer problem I think. Although it's complaining that it doesn't have a decoder for audio/x-unknown, which baffles me.

**Comment by jghibiki** [comment]
I am seeing this same audio/x-unknown issue for [this video](https://www.youtube.com/watch?v=8xXOYmGzKCo) as well. Other videos however play just fine (with an occasional hiccup like this one).

I am seeing this issue on Debian GNU/Linux 7.

**Comment by dz0ny** [comment]
```ERROR    Your GStreamer installation is missing a plug-in.```

That means you need to install gstreamer-plugins-{bad,ugly,unsupported...} the best is to install all plugins that there are for GStreamer :)

**Comment by jghibiki** [comment]
@dz0ny I tried that to no avail.

**Comment by kgudka** [comment]
Yes I also tried installing every gstreamer plugin but it still didn't help. I think the problem is that the mime type is audio/x-unknown and so it can't find a plugin for it?

**Comment by jodal** [comment]
If you're installing GStreamer from Homebrew, there's lots of optional dependencies that are not included by default. The mopidy/mopidy/mopidy Homebrew formula does a good job at install GStreamer with a logn list of useful extras, ref. https://github.com/mopidy/homebrew-mopidy/blob/17b1d11924005fd34e6a0f602589b721b0cc2f1d/mopidy.rb#L10-L36

Thus, I'd recommend uninstalling GStreamer and installing mopidy/mopidy/mopidy to let it handle the optional GStreamer parts:

```
brew uninstall gst-plugins-base010 gst-plugins-good010 gst-plugins-bad010 gst-plugins-ugly010
brew install mopidy/mopidy/mopidy
```

**Comment by kgudka** [comment]
That appears to have fixed it for me.

Thanks!

**Comment by jodal** [comment]
Great! :-)
