### ISSUE TITLE
Youtube playlist links don't work within m3u playlist

### ISSUE THREAD

**Issue by Xandaros** [mopidy/mopidy-youtube#51]
If you put a YouTube playlist URL of the form `yt:http://www.youtube.com/playlist?list=<listId>` or `yt:http://www.youtube.com/watch?v=<videoId>&list=<listId>` in a M3U-playlist, it doesn't actually add anything to the queue when you try to play it.

The only log output this adds is these three lines:
```
Jan 05 18:46:01 radio mopidy[20098]: ERROR    WebSocket request error: Expected album to be a <class 'mopidy.models.Album'>, not {u'uri': u'x', u'name': u''}
Jan 05 18:46:01 radio mopidy[20098]: ERROR    WebSocket request error:
Jan 05 18:46:01 radio mopidy[20098]: ERROR    WebSocket request error:
```

**Comment by kingosticks** [comment]
The error message is due to some bad handling of playlist tracks in musicbox-webclient following the move to stricter model validation in Mopidy (ages ago) see https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/131. I should have spotted that on IRC, sorry.

**Comment by Xandaros** [comment]
Well, it also doesn't work when using the mpd frontend. I actually disabled musicbox to make sure it doesn't interfere.
(Though those error messages are indeed caused by musicbox.)

I have also noticed, that it doesn't work even when making an M3U playlist with just a single video in it: https://gist.github.com/Xandaros/e2f4c546fba9c4f6d85b
I tried it both with and without the `yt:` prefix.

**Comment by Xandaros** [comment]
Turns out I'm just too stupid to use playlists. Apparently you use `load <playlist>`, not `playlist <playlist>`.
Interesting how nobody called me out on that, though.
