### ISSUE TITLE
 Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))

### ISSUE THREAD

**Issue by HawkingJan** [mopidy/mopidy-youtube#55]
I'm using modipy (Version 2.0) on a RaspberryPi (Raspbian Jessie) and accessing it via the Mopidy-MusicBox-Webclient. Besides other software I have Mopidy-Youtube (Version 2.0.2), pafy (0.4.3) and youtube-dl (2016.2.13) installed. 
After I installed certifi==2015.4.28 my YouTube search is working again (see #54 ) and with Mopidy 2.0 I can even listen to the found results but I also get the error message I had before back:

```
Feb 18 11:19:35 sys mopidy[469]: INFO     Searching YouTube for query 'test'
Feb 18 11:20:00 sys mopidy[469]: ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
Feb 18 11:20:00 sys mopidy[469]: INFO     ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
Feb 18 11:20:00 sys mopidy[469]: ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
Feb 18 11:20:00 sys mopidy[469]: INFO     ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
....
```

Is this "normal" (as I said, the search is slow but seems to be working) or should I do something about it?

**Comment by jodal** [comment]
This looks like a DNS lookup problem, which is related to your system's setup or your ISP's DNS server. 

Closing as this is probably not an issue with Mopidy-YouTube, but feel free to ask for help at https://discuss.mopidy.com.
