### ISSUE TITLE
fixture 'caplog' not found

### ISSUE THREAD

**Issue by AndreMiras** [mopidy/mopidy-youtube#63]
I've cloned the latest mopidy-youtube and I wanted to run tests, but I got the error below:
<pre>
$ py.test
============================================================================================================================ test session starts ============================================================================================================================
platform linux2 -- Python 2.7.9, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/pi/Progz/SoundServer/code/mopidy-youtube, inifile: 
collected 8 items 

tests/test_backend.py ......E
tests/test_extension.py .

================================================================================================================================== ERRORS ===================================================================================================================================
__________________________________________________________________________________________________________________ ERROR at setup of test_lookup_video_uri __________________________________________________________________________________________________________________
file /home/pi/Progz/SoundServer/code/mopidy-youtube/tests/test_backend.py, line 81
  @vcr.use_cassette('tests/fixtures/lookup_video_uri.yaml')
  def test_lookup_video_uri(caplog):
        fixture 'caplog' not found
        available fixtures: tmpdir_factory, pytestconfig, pafy_mock_with_video, cache, recwarn, pafy_mock, monkeypatch, record_xml_property, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.

/home/pi/Progz/SoundServer/code/mopidy-youtube/tests/test_backend.py:81
===================================================================================================================== 7 passed, 1 error in 3.77 seconds =====================================================================================================================
</pre>

Additional information:
<pre>
$ python --version
Python 2.7.9
$ git log -n 1 
commit bf378f9f83db91f336e8168a4aa236135be604d0
Author: Nick Steel <nsteel@fastmail.com>
Date:   Fri Apr 15 16:58:42 2016 +0100

    Travis builds require trusty (part 2)
</pre>

**Comment by Chateaudur** [comment]
Hi,
I have no idea if that could help you but I had another issue with the test fw and paffy... Someone gave me answer for #62 , maybe you could try (suggests using tox). 
Also if you happen to have an idea on my problem, I'm all ears :)

**Comment by jodal** [comment]
You need to install `pytest-capturelog`. Even better, just run the tests using tox, as it will install all the requirements needed to run tests in a virtualenv. See the file `tox.ini` in the root of the repo for a list of all test dependencies.

**Comment by AndreMiras** [comment]
Thank you for ```pytest-capturelog```. Yes I first tried with tox, but I got even more errors, so I wanted to give it a go manually.
