### ISSUE TITLE
Using search causes mopidy to stop

### ISSUE THREAD

**Issue by m-kostrzewa** [mopidy/mopidy-youtube#76]
Hello, I encountered an issue when trying to use containerized version of mopidy. Using the "search" feature of the web client crashes mopidy.

Here's the original issue: https://github.com/wernight/docker-mopidy/issues/7

I did some investigating, and it seems like mopidy-youtube caues the problem.

This is the last lines mopidy outputs before crashing:
```
DEBUG    2017-02-19 18:21:46,597 [1:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.library.search","params":{"any":["asdf"]},"jsonrpc":"2.0","id":56}'
INFO     2017-02-19 18:21:46,605 [1:YouTubeBackend-3] mopidy_youtube
  Searching YouTube for query 'asdf'
```

```-o youtube/enabled=false``` fixes the problem, but I can't search for youtube videos :(

Tried playing with pafy and youtube-dl using pip, and also confirmed that I can get youtube video info using pafy. More details in linked issue.

**Comment by kingosticks** [comment]
When you say it crashes, do you mean it actually crashes? Do you have a stack trace or a core dump?

**Comment by m-kostrzewa** [comment]
The docker container stops, as if the app was stopped

**Comment by m-kostrzewa** [comment]
Turns out it was an issue with kernel security (PaX). Running this on linux alpine solves the problem:
```
sysctl -w kernel.pax.softmode=1
```
