### ISSUE TITLE
Could not establish connection when streaming youtube

### ISSUE THREAD

**Issue by jaminh** [mopidy/mopidy-youtube#79]
When trying to stream youtube I get the following error:

mopidy.audio.gst: GStreamer error: gst-resource-error-quark: Could not establish connection to server. (5)

It appears it is having problems connecting to r7---sn-bvvbax-nual.googlevideo.com.

Mopidy (2.1.0)
Mopidy-Youtube (2.0.2)
youtube-dl (2017.6.12)

**Comment by kingosticks** [comment]
That sort of sounds like an upstream problem. Have you tried asking the
youtube-dl project?

**Comment by jaminh** [comment]
Looks like my issue may be related to https://github.com/rg3/youtube-dl/issues/9477, but the "Network Unreachable" might just be caused by my network lacking IPv6. Using IPv4 only it appears the issue may actually be related to https://github.com/rg3/youtube-dl/issues/4678.
