### ISSUE TITLE
support for shortened url's

### ISSUE THREAD

**Issue by amfasis** [mopidy/mopidy-youtube#83]
Currently Mopidy-youtube does not support shortened URL's like youtu.be, which are used for example from the android youtube app when sharing a video

**Comment by kingosticks** [comment]
It doesn't currently support any URIs starting with 'http', shortened or otherwise. These are always handled by the http extension and that's a more fundamental Mopidy restriction.

**Comment by amfasis** [comment]
Ok, I understand that. Does it help when I put yt: in front?

**Comment by kingosticks** [comment]
OK, so to be clear:
This currently works: `mpc add "yt:https://www.youtube.com/watch?v=iuWa5wh8lG0"`
This doesn't: `mpc add "yt:https://youtu.be/iuWa5wh8lG0"`

Seems like a good improvement to make.

**Comment by kingosticks** [comment]
So having actually tested this, this already works.... Is there actually anything to do here?

**Comment by amfasis** [comment]
hmm, when I try it I get the following error: Need 11 character video id or the URL of the video. Got //be/pH8GejP-G2o

btw, I'm doing this through the musicbox-webclient

**Comment by kingosticks** [comment]
Through the streams page? Is it the latest version?

How the individual web clients / frontends use the core API varies.

**Comment by amfasis** [comment]
yes it is the latest version, installed this week.
I'm a bit lost now actually, it has worked but now it doesn't do any version of youtube URL I put in. When I put the normal version it errors with `unknown url type: /yts/jsbin/player-vfl1RKjMF/nl_NL/base.js`

I did execute `apt-get remove mopidy-youtube` and then did `pip install mopidy-youtube`.
What are the differences between these two ways of installing?

**Comment by kingosticks** [comment]
Unless you using apt.mopidy.com, installing from APT usually installs old versions. APT handles all dependencies but pip only handles python dependencies, if your package requires anything else (e.g. libspotify for mopidy-spotify) then you need to install it manually (usually through APT). I don't think that is the case with mopidy-youtube. 

If you run `mopidy deps` it will show you exactly what is being used and you could compare the two installation methods, if you wanted. I have included my versions below:
```
Mopidy-Youtube: 2.0.1 from /work/nsteel/projects/mopidy-dev/mopidy-youtube
  setuptools: 34.3.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
    appdirs>=1.4.0: 1.4.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
    packaging>=16.8: 16.8 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      pyparsing: 2.2.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      six: 1.10.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
    six>=1.6.0: 1.10.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
  requests>=2.2.1: 2.13.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
  pafy>=0.3.35: 0.5.3.1 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
  Mopidy>=1.0: 2.1.0 from /work/nsteel/projects/mopidy-dev/mopidy
    Pykka>=1.1: 1.2.1 from /work/nsteel/projects/mopidy-dev/pykka
    requests>=2.0: 2.13.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
    setuptools: 34.3.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      appdirs>=1.4.0: 1.4.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      packaging>=16.8: 16.8 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
        pyparsing: 2.2.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
        six: 1.10.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      six>=1.6.0: 1.10.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
    tornado>=3.2: 4.4.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      certifi: 2017.1.23 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
        six: 1.10.0 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
      backports-abc>=0.4: 0.5 from /home/nsteel/.virtualenvs/mopidy/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.1 from /work/nsteel/projects/mopidy-dev/pykka

```

I don't have any issue entering either of the following URIs into the musicbox-webclient Streams page box:
* yt:https://www.youtube.com/watch?v=iuWa5wh8lG0
* yt:https://youtu.be/iuWa5wh8lG0

**Comment by amfasis** [comment]
I do use apt.mopidy.com and the versions from your `mopidy deps` match quite ok, only setuptools is 5.5.1 for me, but I don't really see why that could cause this problem.

Anyway, thanks for the help. I think I will completely remove it and begin from scratch to hopefully resolve the issue for me as well. Since you have it working, I'm ok closing the issue

**Comment by amfasis** [comment]
did a complete uninstall and install and updated setuptools and requests, now it works!
